[workspace]
resolver = "2"
members = [
    "crates/chronos-protocol",
    "crates/chronos-sim",
    "crates/chronos-node",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
disallowed_types = "deny"
disallowed_methods = "deny"
